# Generated by Django 6.0 on 2026-01-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0002_inversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='ultimo_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
