# Generated by Django 5.2.6 on 2026-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0002_cuentausuario_retiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recarga',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='recarga',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='recarga',
            name='numero_cuenta',
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='duracion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recarga',
            name='estado',
            field=models.CharField(choices=[('revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='revision', max_length=15),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='estado',
            field=models.CharField(default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
