# Generated by Django 6.0 on 2026-01-23 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0003_remove_recarga_banco_remove_recarga_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
