# Generated by Django 6.0 on 2026-01-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0004_usuario_referido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bono_primera_recarga',
            field=models.BooleanField(default=False),
        ),
    ]
