# Generated by Django 5.2.6 on 2026-01-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0005_usuario_bono_primera_recarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recarga_comision_pagada',
            field=models.BooleanField(default=False),
        ),
    ]
