# Generated by Django 5.2.6 on 2026-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0006_usuario_recarga_comision_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='dias_pagados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inversion',
            name='ganancia_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
