# Generated by Django 5.2.6 on 2026-01-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0007_inversion_dias_pagados_inversion_ganancia_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inverso_sa.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
