# Generated by Django 6.0 on 2026-01-29 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0008_transaccion_cuenta_transaccion_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionReferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('invitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('referido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_generadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
